name: flutter_application
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.24.2 # Firebase Core versi terbaru saat ini
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.6.0
  fluttertoast: ^8.2.4 # Gunakan versi terbaru yang kompatibel dengan Flutter saat ini

  # Public API
  weather: 3.1.1 # Example: Set specific versions that you know work together
  google_fonts: ^6.1.0
  intl: ^0.19.0 # Sesuaikan dengan dependensi yang diperlukan oleh paket lain
  curved_navigation_bar: ^1.0.3
  convex_bottom_bar: ^3.2.0
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.0
  provider: ^6.1.1 # Perbarui ke versi terbaru jika tersedia
  shared_preferences: ^2.0.11
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/profil.png
    - assets/apku_logo.JPG
    - assets/foto_profil.jpg
